service: cosva-infra

custom:
  stage: ${opt:stage, 'dev'}
  region:
    prod: us-east-1
    default: us-east-1
  logRetention:
    prod: 180
    default: 14
  databaseName: 'cosva${self:custom.stage}'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:service}-${self:custom.stage}
  stackTags:
    STAGE: ${self:custom.stage}
  logs:
    restApi: true
  logRetentionInDays: ${self:custom.logRetention.${self:custom.stage}, self:custom.logRetention.default}

package:
  exclude:
    - node_modules/**
    - set_env_vars.sh
    - package.json
    - package-lock.json
    - README.md

resources:
  - ${file(resources/stackinfo.yml)}
  - ${file(resources/DB.yml)}
  # Log Groups
  - ${file(resources/loggroups/LogGroups.yml)}
