Resources:
  # Info about this resource below
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html
  ClusterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:provider.stackName}-db-secret
      Description: 'This is the Master secret for the RDS Aurora cluster'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "cosva"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  LightSailDB:
    Type: AWS::Lightsail::Database
    Properties:
      AvailabilityZone: ${self:provider.region}a
      MasterUsername:
        !Join [
          '',
          [
            '{{resolve:secretsmanager:',
            !Ref ClusterSecret,
            ':SecretString:username}}',
          ],
        ]
      MasterUserPassword:
        !Join [
          '',
          [
            '{{resolve:secretsmanager:',
            !Ref ClusterSecret,
            ':SecretString:password}}',
          ],
        ]
      RelationalDatabaseBlueprintId: postgres_15
      RelationalDatabaseBundleId: micro_2_0
      RelationalDatabaseName: ${self:custom.databaseName}
      MasterDatabaseName: ${self:custom.databaseName}
      BackupRetention: true
      Tags:
        - Key: Name
          Value: ${self:provider.stackName}

Outputs:
  ClusterSecret:
    Description: Secret de la base de datos creada en CloudFormation
    Value: !Ref ClusterSecret

  LightSailDB:
    Description: Base de datos creada en Lightsail
    Value: !Ref LightSailDB
